version: '2'
services:
    db:
        image: mariadb
        restart: always
        volumes:
        - ./mysql/initdb/:/docker-entrypoint-initdb.d
        - ./mysql/data/:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=yourls
        - MYSQL_USER=yourls
        - MYSQL_PASSWORD=yourls
    php:
        image: bordin/php-7-fpm-alpine
        volumes:
        - ./YOURLS:/var/www/s/
        expose:
        - "9000"
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/:/etc/nginx/conf.d:ro
        volumes_from:
        - php
        ports:
        - 80:80
        - 443:443